import { ShieldCheck, Database, Cpu, Code2 } from "lucide-react";

function About() {
  return (
    <div className="page">
      <h2>About CyberPulse</h2>
      <p>Your Intelligent Cybersecurity News Intelligence Dashboard.</p>

      <div className="about-grid">
        <div className="card about-card">
          <ShieldCheck className="about-icon" size={24} />
          <h3>Purpose</h3>
          <p>
            CyberPulse is a college mini-project that collects, organizes,
            and analyzes real cybersecurity news into an easy-to-understand
            dashboard, helping users stay aware of current threats without
            needing deep security expertise.
          </p>
        </div>

        <div className="card about-card">
          <Database className="about-icon" size={24} />
          <h3>Data Sources</h3>
          <p>
            News is pulled live from The Hacker News and BleepingComputer via
            RSS feeds. Vulnerability data comes from the National
            Vulnerability Database (NVD), a real, official U.S. government
            source. No article content or incident data is fabricated.
          </p>
        </div>

        <div className="card about-card">
          <Cpu className="about-icon" size={24} />
          <h3>AI Integration</h3>
          <p>
            The AI Cyber Threat Analyzer uses a rule-based, explainable
            analysis engine — it examines each article's real text to
            determine severity, attack type, affected sector, and generate
            plain-language summaries and recommendations. This keeps the
            demo fast, free, and fully offline-capable, with an architecture
            that could be swapped for a live LLM API in the future.
          </p>
        </div>

        <div className="card about-card">
          <Code2 className="about-icon" size={24} />
          <h3>Technology Stack</h3>
          <p>
            Built with React + Vite on the frontend, Node.js + Express on
            the backend, styled with custom CSS, charted with Recharts, and
            iconography from Lucide React.
          </p>
        </div>
      </div>

      <div className="card disclaimer-card">
        <h3>Disclaimer</h3>
        <p>
          Threat levels, cyber threat scores, and trending topic counts
          shown throughout this application are generated by CyberPulse's
          own keyword-based analysis logic. They are application-generated
          assessments intended for educational purposes, not official
          security ratings or verified incident data. For authoritative
          vulnerability information, always refer to the linked NVD source
          pages directly.
        </p>
      </div>
    </div>
  );
}

export default About;