import { useState, useEffect } from "react";
import { Newspaper, CalendarDays, AlertTriangle, Tag } from "lucide-react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  CartesianGrid,
} from "recharts";
import { getAllNews } from "../services/newsService";
import { CATEGORIES, detectCategory } from "../utils/categorize";
import { getSeverity } from "../utils/severity";
import StatCard from "../components/StatCard";
import LoadingSkeleton from "../components/LoadingSkeleton";
import ErrorState from "../components/ErrorState";

function isToday(dateString) {
  if (!dateString) return false;
  const date = new Date(dateString);
  const today = new Date();
  return (
    date.getDate() === today.getDate() &&
    date.getMonth() === today.getMonth() &&
    date.getFullYear() === today.getFullYear()
  );
}

function Dashboard() {
  const [articles, setArticles] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [lastUpdated, setLastUpdated] = useState(null);

  useEffect(() => {
    async function loadNews() {
      try {
        setLoading(true);
        const data = await getAllNews();
        const tagged = data.map((article) => {
          const severity = getSeverity(article);
          return {
            ...article,
            category: detectCategory(article),
            severityLevel: severity.level,
            severityScore: severity.score,
          };
        });
        setArticles(tagged);
        setLastUpdated(new Date());
        setError(null);
      } catch (err) {
        setError("Could not load dashboard data. Is the backend server running?");
      } finally {
        setLoading(false);
      }
    }

    loadNews();
  }, []);

  const totalArticles = articles.length;
  const todaysArticles = articles.filter((a) => isToday(a.publishedAt)).length;

  const criticalThreats = articles.filter(
    (a) => a.severityLevel === "CRITICAL" || a.severityLevel === "HIGH"
  ).length;

  const categoriesUsed = new Set(articles.map((a) => a.category)).size;

  const categoryChartData = CATEGORIES.map((cat) => ({
    name: cat,
    count: articles.filter((a) => a.category === cat).length,
  })).filter((entry) => entry.count > 0);

  const latestArticles = [...articles]
    .sort((a, b) => new Date(b.publishedAt) - new Date(a.publishedAt))
    .slice(0, 5);

  if (loading) {
    return (
      <div className="page">
        <h2>Dashboard</h2>
        <p>Overview of current cybersecurity news activity.</p>
        <LoadingSkeleton type="stats" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="page">
        <h2>Dashboard</h2>
        <ErrorState message={error} onRetry={() => window.location.reload()} />
      </div>
    );
  }
  return (
    <div className="page">
      <div className="dashboard-header">
        <div>
          <h2>Dashboard</h2>
          <p>Overview of current cybersecurity news activity.</p>
        </div>
        {lastUpdated && (
          <p className="last-updated">
            Last updated: {lastUpdated.toLocaleTimeString()}
          </p>
        )}
      </div>

      <div className="stats-grid">
        <StatCard
          icon={Newspaper}
          label="Total Articles"
          value={totalArticles}
          accentColor="#60a5fa"
        />
        <StatCard
          icon={CalendarDays}
          label="Today's News"
          value={todaysArticles}
          accentColor="#22c55e"
        />
        <StatCard
          icon={AlertTriangle}
          label="Critical / High Threats"
          value={criticalThreats}
          accentColor="#f97316"
        />
        <StatCard
          icon={Tag}
          label="Categories Active"
          value={categoriesUsed}
          accentColor="#a78bfa"
        />
      </div>

      <p className="chart-disclaimer">
        Severity levels are generated by CyberPulse's rule-based keyword
        analysis of each article's title and description. This is an
        application-generated assessment, not an official security rating.
      </p>

      <div className="dashboard-grid">
        <div className="card chart-card">
          <h3>Category Distribution</h3>
          <ResponsiveContainer width="100%" height={280}>
            <BarChart data={categoryChartData} layout="vertical" margin={{ left: 20 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.06)" />
              <XAxis type="number" stroke="#8b96a5" fontSize={12} allowDecimals={false} />
              <YAxis
                type="category"
                dataKey="name"
                stroke="#8b96a5"
                fontSize={12}
                width={110}
              />
              <Tooltip
                contentStyle={{
                  background: "#131a24",
                  border: "1px solid rgba(255,255,255,0.08)",
                  borderRadius: "8px",
                  color: "#e6edf3",
                }}
              />
              <Bar dataKey="count" fill="#3b82f6" radius={[0, 4, 4, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>

        <div className="card latest-card">
          <h3>Latest News</h3>
          <ul className="latest-list">
            {latestArticles.map((article) => (
              <li key={article.id} className="latest-item">
                <span className="latest-source">{article.source}</span>
                <a
                  href={article.link}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="latest-title"
                >
                  {article.title}
                </a>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
}

export default Dashboard;